export const TIPOS_PERGUNTAS = [
  {
    key: 'SH',
    label: 'Fraquezas e Ameaças sem histórias sociais',
    endpoint: '/fraquezas-ameacas-sh',
    campoTexto: 'pergunta',
    campoOrdem: 'numeroTraco',
    campos: [
      { name: 'numeroTraco', label: 'Ordem',                  type: 'number',   required: true },
      { name: 'pergunta',    label: 'Pergunta',               type: 'textarea', required: true },
      { name: 'explicacao',  label: 'Explicação',             type: 'textarea', required: false },
      { name: 'swot',        label: 'Apresentação no SWOT',   type: 'textarea', required: false },
      { name: 'frequencia',  label: 'Frequência',             type: 'number',   required: false },
      { name: 'intensidade', label: 'Intensidade',            type: 'number',   required: false },
    ],
  },
  {
    key: 'CH',
    label: 'Fraquezas e Ameaças com histórias sociais',
    endpoint: '/fraquezas-ameacas-ch',
    campoTexto: 'swot',
    campoOrdem: 'numeroTraco',
    campos: [
      { name: 'numeroTraco', label: 'Ordem',                   type: 'number',   required: true },
      { name: 'numHistoria', label: 'Nº História',             type: 'number',   required: true },
      { name: 'frequencia',  label: 'Frequência',              type: 'number',   required: true },
      { name: 'intensidade', label: 'Intensidade',             type: 'number',   required: true },
      { name: 'swot',        label: 'Apresentação no SWOT',    type: 'textarea', required: false },
    ],
  },
  {
    key: 'FO',
    label: 'Fraquezas e Oportunidades',
    endpoint: '/fraquezas-oportunidades',
    campoTexto: 'pergunta',
    campoOrdem: 'numeroTraco',
    campos: [
      { name: 'numeroTraco',       label: 'Ordem',                  type: 'number',   required: true },
      { name: 'pergunta',          label: 'Pergunta',               type: 'textarea', required: true },
      { name: 'explicacao',        label: 'Explicação',             type: 'textarea', required: false },
      { name: 'swot',              label: 'Apresentação no SWOT',   type: 'textarea', required: false },
      { name: 'tracoNeutro',       label: 'Traço Neutro',           type: 'array',    required: false },
      { name: 'tracoOportunidade', label: 'Traço Oportunidade',     type: 'array',    required: false },
      { name: 'tracoFraqueza',     label: 'Traço Fraqueza',         type: 'array',    required: false },
    ],
  },
  {
    key: 'F',
    label: 'Forças',
    endpoint: '/forcas',
    campoTexto: 'pergunta',
    campoOrdem: 'numeroTraco',
    campos: [
      { name: 'numeroTraco',       label: 'Ordem',                  type: 'number',   required: true },
      { name: 'pergunta',          label: 'Pergunta',               type: 'textarea', required: true },
      { name: 'exemplo',           label: 'Exemplo',                type: 'textarea', required: false },
      { name: 'swot',              label: 'Apresentação no SWOT',   type: 'textarea', required: false },
      { name: 'tracoNeutro',       label: 'Traço Neutro',           type: 'array',    required: false },
      { name: 'tracoForca',        label: 'Traço Força',            type: 'array',    required: false },
      { name: 'tracoFraqueza',     label: 'Traço Fraqueza',         type: 'array',    required: false },
      { name: 'tracoOportunidade', label: 'Traço Oportunidade',     type: 'array',    required: false },
    ],
  },
  {
    key: 'HS',
    label: 'Histórias Sociais',
    endpoint: '/historias-sociais',
    campoTexto: 'titulo',
    campoOrdem: 'numeroHistoria',
    campos: [
      { name: 'numeroHistoria',      label: 'Ordem',                    type: 'number',   required: true },
      { name: 'titulo',              label: 'Título',                   type: 'text',     required: true },
      { name: 'introducao',          label: 'Introdução',               type: 'textarea', required: true },
      { name: 'personagem',          label: 'Personagem',               type: 'text',     required: true },
      { name: 'ambientacao',         label: 'Ambientação',              type: 'textarea', required: true },
      { name: 'historia',            label: 'História',                 type: 'textarea', required: true },
      { name: 'questionamento',      label: 'Questionamento',           type: 'textarea', required: true },
      { name: 'perguntaIntensidade', label: 'Pergunta de Intensidade',  type: 'textarea', required: true },
      { name: 'intensidadeLeve',     label: 'Intensidade Leve',         type: 'textarea', required: true },
      { name: 'intensidadeModerada', label: 'Intensidade Moderada',     type: 'textarea', required: true },
      { name: 'intensidadeAlta',     label: 'Intensidade Alta',         type: 'textarea', required: true },
    ],
  },
]
